inp1 = str(input())
if inp1=="Hi" or "Hai" or "hello":
    print("Hello")
print("Could you please mention your laptop company among them")
print("1. HP")
print("2. DELL")
print("3. LENOVO")
print("4. ASUS")
print("5. APPLE")
print("6. MI")
print("7. REALME")
print("8. SONY")
print("9. Others")
choice=int(input("ENTER YOUR CHOICE\n"))
if choice==1:
    print("Choose your model")
    print("1. Pavelion")
    print("2. Envy")
    print("3. HP Essentials")
    print("4. Chrome Book")
    print("5. Elite Book")
    modelchoice=int(input("Enter Your Choice\n"))
    if modelchoice==1:
        print("What is the problem in your device?\nChoose from the below")
        print("1. not starting")
        print("2. Continuous restarts")
        print("")